project_id = "cfecicvugfrrhcvhduzc"

[functions.initialize-exam-payment]
verify_jwt = false

[functions.verify-exam-payment]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false

[functions.initialize-certificate-payment]
verify_jwt = false

[functions.verify-certificate-payment]
verify_jwt = false

[functions.paystack-certificate-webhook]
verify_jwt = false

[functions.agilecert-communications]
verify_jwt = false

[functions.agilecert-communications-control]
verify_jwt = false

[functions.agilecert-resend-webhook]
verify_jwt = false
