import { useEffect, useState } from 'react';
import { BookOpenCheck, CheckCircle2, FileText, LockKeyhole, Play } from 'lucide-react';
import { getAvailableTests, startCipmnTheoryRetake } from '../services/examService';
import type { CipmnSectionProgress } from '../types';

interface Props { examinationId:string; moduleTitle:string; materialsUnlocked:boolean; examUnlocked:boolean; onAttemptMcq?:()=>void; onStartTheory?:()=>void; }
export default function CipmnModuleHubContext({examinationId,moduleTitle,materialsUnlocked,examUnlocked,onAttemptMcq,onStartTheory}:Props){
 const [progress,setProgress]=useState<CipmnSectionProgress|null>(null); const [retakeBusy,setRetakeBusy]=useState(false); const [retakeError,setRetakeError]=useState<string|null>(null);
 const canAttemptMcq=examUnlocked&&typeof onAttemptMcq==='function';
 const theoryCompleted=Boolean(progress?.theoryCompleted&&progress.currentSection==='complete'&&progress.sessionStatus==='submitted');
 const theoryReady=!theoryCompleted&&Boolean(progress?.theoryReady&&progress.currentSection==='theory'&&progress.sessionStatus==='active');
 const canUseTheory=examUnlocked&&typeof onStartTheory==='function';
 const canStartTheory=theoryReady&&canUseTheory;
 useEffect(()=>{let disposed=false;const refresh=async()=>{try{const tests=await getAvailableTests();if(!disposed)setProgress(tests.find(t=>t.id===examinationId)?.sectionProgress||null);}catch(e){console.error('Unable to refresh CIPMN module section progress.',e);}};void refresh();const handler=()=>void refresh();window.addEventListener('iipm-commerce-refresh',handler);window.addEventListener('focus',handler);return()=>{disposed=true;window.removeEventListener('iipm-commerce-refresh',handler);window.removeEventListener('focus',handler);};},[examinationId]);
 const retakeTheory=async()=>{if(!canUseTheory||retakeBusy)return;setRetakeBusy(true);setRetakeError(null);try{await startCipmnTheoryRetake(examinationId);window.dispatchEvent(new Event('iipm-commerce-refresh'));onStartTheory();}catch(e){setRetakeError(e instanceof Error?e.message:'Unable to start the Theory retake.');setRetakeBusy(false);}};
 return <section className="mt-4 rounded-xl border border-slate-200 bg-slate-50/70 p-3" aria-label={`CIPMN module hub for ${moduleTitle}`} data-agilecert-cipmn-module-hub="true">
  <div className="mb-2 flex items-center justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Module Hub</p><p className="text-xs font-semibold text-slate-700">{moduleTitle}</p></div><span className="rounded-full border border-slate-200 bg-white px-2 py-1 text-[10px] font-semibold text-slate-500">Preparation & Assessment</span></div>
  <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">
   <div className="rounded-lg border border-slate-200 bg-white p-2.5"><div className="flex items-center gap-1.5 text-xs font-bold text-slate-700"><BookOpenCheck className="h-3.5 w-3.5"/> Materials</div><p className="mt-1 text-[10px] text-slate-500">{materialsUnlocked?'Available for this module':'Available after payment'}</p></div>
   <div className="rounded-lg border border-slate-200 bg-white p-2.5"><div className="flex items-center gap-1.5 text-xs font-bold text-slate-700">{examUnlocked?<FileText className="h-3.5 w-3.5"/>:<LockKeyhole className="h-3.5 w-3.5"/>} MCQs</div><button type="button" disabled={!canAttemptMcq} onClick={canAttemptMcq?onAttemptMcq:undefined} className="mt-2 w-full rounded-md border border-slate-200 bg-slate-900 px-2 py-1.5 text-[10px] font-bold text-white transition enabled:hover:bg-slate-800 disabled:cursor-not-allowed disabled:bg-slate-100 disabled:text-slate-400" data-agilecert-cipmn-attempt-mcq="true">{examUnlocked?(progress?.mcqCompleted?'Retake MCQs':'Attempt MCQs Now'):'MCQs Locked'}</button></div>
   <div className={`rounded-lg border p-2.5 ${theoryReady||theoryCompleted?'border-emerald-200 bg-emerald-50/60':'border-slate-200 bg-white'}`}><div className={`flex items-center gap-1.5 text-xs font-bold ${theoryReady||theoryCompleted?'text-emerald-800':'text-slate-700'}`}>{theoryCompleted?<CheckCircle2 className="h-3.5 w-3.5"/>:theoryReady?<FileText className="h-3.5 w-3.5"/>:<LockKeyhole className="h-3.5 w-3.5"/>} Theory</div>
    {theoryCompleted?<><p className="mt-1 text-[10px] font-semibold text-emerald-700">Theory section completed</p><button type="button" disabled={!canUseTheory||retakeBusy} onClick={()=>void retakeTheory()} className="mt-2 flex w-full items-center justify-center gap-1 rounded-md bg-emerald-700 px-2 py-1.5 text-[10px] font-bold text-white transition enabled:hover:bg-emerald-800 disabled:cursor-not-allowed disabled:bg-slate-100 disabled:text-slate-400" data-agilecert-cipmn-retake-theory="true"><Play className="h-3 w-3 fill-current"/> {retakeBusy?'Opening Theory…':'Retake Theory'}</button>{retakeError?<p className="mt-1 text-[9px] font-semibold text-red-600">{retakeError}</p>:null}</>:theoryReady?<><p className="mt-1 text-[10px] font-semibold text-emerald-700">MCQs completed — Theory ready</p><button type="button" disabled={!canStartTheory} onClick={canStartTheory?onStartTheory:undefined} className="mt-2 flex w-full items-center justify-center gap-1 rounded-md bg-emerald-600 px-2 py-1.5 text-[10px] font-bold text-white transition enabled:hover:bg-emerald-700 disabled:cursor-not-allowed disabled:bg-slate-100 disabled:text-slate-400" data-agilecert-cipmn-start-theory="true"><Play className="h-3 w-3 fill-current"/> Start Theory Now</button></>:<p className="mt-1 text-[10px] text-slate-500">Complete MCQs to unlock</p>}
   </div>
   <div className="rounded-lg border border-slate-200 bg-white p-2.5"><div className="flex items-center gap-1.5 text-xs font-bold text-slate-700"><CheckCircle2 className="h-3.5 w-3.5"/> Results</div><p className="mt-1 text-[10px] text-slate-500">Existing attempts remain authoritative</p></div>
  </div>
 </section>;
}
