import type { Question } from './types';

export const cipmnMod001Mcqs: Question[] = [
  { id:'cipmn001-mcq-01', text:'Which statement best distinguishes a project from routine organizational operations?', options:['A project consists primarily of repetitive activities performed continuously.','A project is a temporary and unique initiative with a defined start and finish.','A project has no predetermined resource limitations.','A project continues for as long as the organization remains operational.'], correctOptionIndex:1, type:'mcq', section:'mcq' },
  { id:'cipmn001-mcq-02', text:'A project manager is reviewing a project to ensure that it will be completed on time, within available resources, and according to expected standards. Which purpose of project management is MOST directly reflected?', options:['Eliminating all project uncertainties.','Ensuring timely, cost-effective delivery while maintaining quality.','Converting temporary projects into permanent operations.','Removing stakeholders from project decision-making.'], correctOptionIndex:1, type:'mcq', section:'mcq' },
  { id:'cipmn001-mcq-03', text:'A project team has completed initiation and now needs to establish the project scope, schedule and budget. Which project life-cycle phase should the team enter?', options:['Execution.','Closure.','Planning.','Monitoring and Controlling.'], correctOptionIndex:2, type:'mcq', section:'mcq' },
  { id:'cipmn001-mcq-04', text:'During a road project, management approves a significant expansion of the project scope. According to the triple-constraint concept presented in the module, what should the project manager recognize?', options:['Scope can change without affecting other project constraints.','Changes to scope may affect time and cost.','Only project quality will be affected.','Cost automatically decreases whenever scope increases.'], correctOptionIndex:1, type:'mcq', section:'mcq' },
  { id:'cipmn001-mcq-05', text:'A project manager wants to reduce resistance from an external community that will be affected by a new project. Based on the module, which action is MOST appropriate?', options:['Engage the stakeholders early in the project.','Restrict communication until project closure.','Allow only internal stakeholders to participate.','Engage the community only when a dispute occurs.'], correctOptionIndex:0, type:'mcq', section:'mcq' },
  { id:'cipmn001-mcq-06', text:'A project team has clearly defined its objectives and identified its deliverables. The team now needs to decompose the project into manageable, deliverable-oriented components that will support scheduling and budgeting. What should it develop?', options:['Risk register.','Work Breakdown Structure.','Power-Interest Matrix.','Quality control chart.'], correctOptionIndex:1, type:'mcq', section:'mcq' },
  { id:'cipmn001-mcq-07', text:'For a solar project, the panels must be delivered before installation, while installation must occur before testing. Which planning activity is being applied?', options:['Stakeholder classification.','Activity sequencing.','Project closure.','Resource leveling.'], correctOptionIndex:1, type:'mcq', section:'mcq' },
  { id:'cipmn001-mcq-08', text:'A project has only one qualified electrician, but several activities initially require that electrician at the same time. Which technique described in the module should be used to produce a more balanced workload?', options:['Resource leveling.','Scope expansion.','Project closure.','Stakeholder mapping.'], correctOptionIndex:0, type:'mcq', section:'mcq' },
  { id:'cipmn001-mcq-09', text:'During project implementation, actual progress is compared against established baselines and deviations are discovered. What should project control primarily do next?', options:['Ignore the deviations until project closure.','Apply corrective actions and manage deviations in scope, schedule and budget.','Replace the project objectives with the actual results achieved.','Stop collecting information about project performance.'], correctOptionIndex:1, type:'mcq', section:'mcq' },
  { id:'cipmn001-mcq-10', text:'A project manager needs a visual schedule that shows project activities across time. Which scheduling technique identified in the module is appropriate?', options:['SWOT Analysis.','Gantt Chart.','Risk Assessment Matrix.','Fishbone Diagram.'], correctOptionIndex:1, type:'mcq', section:'mcq' },
  { id:'cipmn001-mcq-11', text:'A project team wants to identify the sequence of activities that determines the critical path of its project schedule. Which technique should it use?', options:['Critical Path Method (CPM).','Total Quality Management.','Power-Interest Matrix.','Resource Allocation.'], correctOptionIndex:0, type:'mcq', section:'mcq' },
  { id:'cipmn001-mcq-12', text:'A project activity has an optimistic duration of 4 days, a most likely duration of 7 days, and a pessimistic duration of 10 days. Using PERT, what is the expected duration of the activity?', options:['6 days.','7 days.','8 days.','9 days.'], correctOptionIndex:1, type:'mcq', section:'mcq' },
  { id:'cipmn001-mcq-13', text:'A project manager is preparing a cost estimate and wants to improve its reliability using information from completed projects. What does the module recommend?', options:['Rely exclusively on current stakeholder opinions.','Use historical data for accuracy.','Remove contingency from the estimate.','Estimate only labour costs.'], correctOptionIndex:1, type:'mcq', section:'mcq' },
  { id:'cipmn001-mcq-14', text:'An organization needs project-management software that improves task visibility while providing real-time dashboards and reports. According to the module, which consideration should ultimately guide its software choice?', options:['The number of stakeholders.','Project complexity.','The project manager job title.','The age of the organization.'], correctOptionIndex:1, type:'mcq', section:'mcq' },
  { id:'cipmn001-mcq-15', text:'Management wants indicators for assessing schedule and cost performance during project implementation. Which pair is explicitly identified in the module?', options:['SWOT and PERT.','SPI and CPI.','PDCA and DMAIC.','WBS and CPM.'], correctOptionIndex:1, type:'mcq', section:'mcq' },
  { id:'cipmn001-mcq-16', text:'Which of the following is identified in the module as a project monitoring tool or technique?', options:['Earned Value Management.','Power-Interest Matrix only.','Employee appraisal.','Organizational restructuring.'], correctOptionIndex:0, type:'mcq', section:'mcq' },
  { id:'cipmn001-mcq-17', text:'A project team has identified a potential threat. According to the risk-management process presented in the module, what should the team do before planning treatment strategies?', options:['Immediately close the project.','Analyze its likelihood and impact, then evaluate and prioritize the threat.','Transfer every identified threat to stakeholders.','Remove the threat from the risk documentation.'], correctOptionIndex:1, type:'mcq', section:'mcq' },
  { id:'cipmn001-mcq-18', text:'A project is experiencing repeated delays, emerging risks and growing dissatisfaction among stakeholders. The technical team insists that its responsibility is limited to completing assigned activities. Based on the project manager responsibilities presented in the module, which response is MOST appropriate?', options:['Concentrate only on technical completion because stakeholder communication belongs to the sponsor.','Monitor progress and risks, lead the team, and actively manage stakeholder communication.','Suspend stakeholder engagement until the project returns to schedule.','Transfer responsibility for project performance to individual team members.'], correctOptionIndex:1, type:'mcq', section:'mcq' },
  { id:'cipmn001-mcq-19', text:'Previous project records show that 4 technicians completed a comparable installation in 2 days under similar conditions and scope. Which planning approach gives the project manager the strongest basis for the initial resource-duration estimate?', options:['Use past project data as the basis for estimating resources and duration.','Ignore previous performance and allocate the maximum available workforce.','Determine the duration only after execution begins.','Estimate the activity solely from the overall budget.'], correctOptionIndex:0, type:'mcq', section:'mcq' },
  { id:'cipmn001-mcq-20', text:'A project estimates labour at ₦4,000,000, materials at ₦8,000,000 and logistics at ₦3,000,000. Management includes a 20% contingency. What should be the resulting project budget?', options:['₦15,000,000.','₦16,500,000.','₦18,000,000.','₦20,000,000.'], correctOptionIndex:2, type:'mcq', section:'mcq' },
  { id:'cipmn001-mcq-21', text:'A project rates four risks on 1–5 probability and impact scales: political instability 3×5, exchange-rate fluctuation 5×4, infrastructure failure 4×4, regulatory delay 2×5. Using Probability × Impact, which risk should receive the highest priority?', options:['Political instability.','Exchange-rate fluctuation.','Infrastructure failure.','Regulatory delay.'], correctOptionIndex:1, type:'mcq', section:'mcq' },
  { id:'cipmn001-mcq-22', text:'A solar-energy project has identified theft of installed solar panels as a significant risk. Which combination most closely follows the risk response presented in the module?', options:['Increase the project budget and discontinue community communication.','Hire local security and engage the community.','Transfer responsibility for the panels to the supplier after installation.','Accept the theft risk because it cannot be completely eliminated.'], correctOptionIndex:1, type:'mcq', section:'mcq' },
  { id:'cipmn001-mcq-23', text:'A project is technically delivering its outputs, but management reports repeated rework, unnecessary waste, inconsistent compliance with required standards and declining stakeholder confidence in output quality. Which management area should receive the most direct attention?', options:['Quality management.','Activity sequencing.','Stakeholder classification.','Resource leveling.'], correctOptionIndex:0, type:'mcq', section:'mcq' },
  { id:'cipmn001-mcq-24', text:'Organization X wants an organization-wide culture of continuous improvement involving employees and customer satisfaction. Organization Y wants targeted, data-driven defect reduction using DMAIC, control charts and process mapping. Which pairing is most consistent with the module?', options:['X = Six Sigma; Y = TQM.','X = TQM; Y = Six Sigma.','X = CPM; Y = TQM.','X = PERT; Y = Six Sigma.'], correctOptionIndex:1, type:'mcq', section:'mcq' },
  { id:'cipmn001-mcq-25', text:'A project team has completed all planned implementation activities. Management now wants the team to deliver the completed outputs, evaluate the results and capture lessons rather than continue treating it as active implementation. Which project life-cycle phase should now receive primary attention?', options:['Initiation.','Planning.','Monitoring and Controlling.','Closure.'], correctOptionIndex:3, type:'mcq', section:'mcq' },
];

export const cipmnMod001Theory: Question[] = [
  { id:'cipmn001-theory-01', type:'theory', section:'theory', text:'A state government has approved a solar-powered rural electrification project for a community. The project has a fixed completion deadline and limited budget. Key stakeholders include government officials, contractors, technicians and members of the beneficiary community. You have been appointed the Project Manager. Explain how you would develop the project plan. Address: (a) appropriate project objectives and major deliverables; (b) how you would use a Work Breakdown Structure (WBS); (c) how activities and dependencies should be identified and sequenced; (d) how resources and duration should be estimated; and (e) how the schedule, budget and major risks would be incorporated into the overall project plan. You are not required to draw a WBS or diagram.', options:[] },
  { id:'cipmn001-theory-02', type:'theory', section:'theory', text:'A project has these activities: A = 3 days (no predecessor); B = 5 days (after A); C = 4 days (after A); D = 6 days (after B); E = 3 days (after C); F = 2 days (after D and E). Using the information provided: (a) identify the possible paths from start to completion; (b) calculate the duration of each path; (c) identify the critical path; (d) determine the minimum expected completion time; and (e) if Activity D is delayed by 3 days, explain the effect on expected completion time. Show calculations in text. You are not required to draw a network diagram.', options:[] },
  { id:'cipmn001-theory-03', type:'theory', section:'theory', text:'A public-sector project is halfway through implementation. Several activities are behind schedule; expenditure is increasing faster than expected; some previously identified risks are occurring; stakeholders complain about inadequate communication; and management is concerned that objectives may not be achieved. As Project Manager: (a) explain how you would assess current performance; (b) identify appropriate performance indicators and monitoring tools covered in the module; (c) distinguish monitoring from control and apply each; (d) recommend practical corrective actions; and (e) explain how continuous stakeholder engagement should contribute to the recovery strategy.', options:[] },
  { id:'cipmn001-theory-04', type:'theory', section:'theory', text:'A major project is experiencing exchange-rate fluctuations affecting procurement costs, regulatory approval delays, infrastructure challenges, repeated defects requiring rework, and growing dissatisfaction with output quality. As Project Manager: (a) identify issues that should be treated primarily as project risks and those requiring quality-management intervention; (b) explain how you would assess and prioritize the risks using likelihood and impact; (c) recommend treatment actions for the most significant risks; (d) explain how quality management could reduce waste and rework; and (e) compare TQM and Six Sigma as presented in the module and explain how either or both could improve quality performance.', options:[] },
  { id:'cipmn001-theory-05', type:'theory', section:'theory', text:'A project team has completed all planned implementation activities and the outputs are ready for delivery. The Project Manager states: “The physical work has been completed, so the project is finished. There is no need for any further evaluation.” Critically assess this position. In your response: (a) identify the lifecycle phase reached; (b) explain what should happen to completed outputs; (c) explain why results should be evaluated; (d) discuss the importance of documenting lessons learned; and (e) explain how effective closure and lessons learned could improve future projects.', options:[] },
];

export const cipmnMod001Questions = [...cipmnMod001Mcqs, ...cipmnMod001Theory];
