begin;

-- CIPMN-MOD-EL05 — ESG in Project Management
-- Sole assessment source:
-- CIPMN-MOD-EL05.pptx (46 slides/pages; reviewed 2026-09-26).

do $guard$
declare
  v_exam_id constant uuid := public.cipmn_mock_seed_uuid('CIPMN-MOD-EL05:EXAM');
begin
  if exists (select 1 from public.examinations where id=v_exam_id or upper(code)='CIPMN-MOD-EL05' or upper(title) like 'CIPMN-MOD-EL05 - %') then raise exception 'CIPMN-MOD-EL05 already exists; creation aborted.'; end if;
end
$guard$;

do $exam$
declare
  v_exam_id constant uuid := public.cipmn_mock_seed_uuid('CIPMN-MOD-EL05:EXAM');
  v_programme_id constant uuid := '614ea9d4-0bd4-5df5-a817-9a93937c74e3';
begin
  insert into public.examinations(id,programme_id,title,instructions,duration_minutes,pass_mark,status,starts_at,ends_at,max_attempts,randomize_questions,randomize_options,created_by,allow_self_enrollment,requires_payment,code,exam_format)
  values(v_exam_id,v_programme_id,'CIPMN-MOD-EL05 - ESG in Project Management Mock Examination','Complete 25 MCQs first, then the 5 Theory questions. The MCQ section contributes 40% and the Theory section contributes 60% of the overall score. This assessment covers ESG fundamentals, sustainability frameworks, Nigerian ESG context, sustainable project management, life-cycle approaches, case studies, EIA/SIA/CSR, governance, compliance, reporting, stakeholder engagement and lifecycle integration. Payment, an applicable coupon or an administrator assignment is required before launch.',120,70.00,'draft',null,null,3,true,true,null,false,true,'CIPMN-MOD-EL05','standard');
end
$exam$;

do $mcq_insert$
declare
  v_exam_id constant uuid := public.cipmn_mock_seed_uuid('CIPMN-MOD-EL05:EXAM');
  v_mcqs jsonb := $mcq$
[
{"position":1,"question":"Which statement best describes ESG as taught in EL05 for sustainable project management?","options":["ESG evaluates environmental, social and governance performance as a holistic sustainability framework.","ESG measures only financial return and schedule performance.","ESG is limited to environmental permitting after project completion.","ESG replaces project governance with corporate philanthropy."],"correct":1},
{"position":2,"question":"Which combination correctly matches the three ESG pillars with examples from EL05?","options":["Environmental—board oversight; Social—pollution; Governance—worker welfare.","Environmental—climate change and pollution; Social—communities, workers and equity; Governance—accountability, board oversight and transparency.","Environmental—taxation; Social—procurement; Governance—biodiversity.","Environmental—profit; Social—planet; Governance—people."],"correct":2},
{"position":3,"question":"What did John Elkington's 1994 Triple Bottom Line framework identify according to the EL05 history?","options":["Risk, Return and Resilience.","Climate, Capital and Compliance.","People, Planet and Profit.","Planning, Procurement and Performance."],"correct":3},
{"position":4,"question":"Which sequence accurately reflects major milestones in the ESG history presented in EL05?","options":["GRI in 1997, PRI in 2006, ISSB established in 2021, and IFRS S1 and IFRS S2 published in 2023.","ISSB in 1987, GRI in 1994, TCFD in 1997, and PRI in 2023.","SASB in 1950, SDGs in 1987, and IFRS S1 in 2006.","TCFD in 1994, GRI in 2006, and ISSB in 2011."],"correct":1},
{"position":5,"question":"Which set contains global ESG reporting and disclosure frameworks specifically identified in EL05?","options":["PMBOK, PRINCE2, ISO 21500 and Scrum.","Nigerian Code of Corporate Governance, CAMA 2020, FIRS and NESREA only.","Equator Principles, procurement thresholds, payroll rules and tax schedules.","Global Reporting Initiative, Sustainability Accounting Standards Board, Task Force on Climate-related Financial Disclosures, and ISSB IFRS S1/IFRS S2."],"correct":4},
{"position":6,"question":"Which statement correctly summarizes the Nigerian ESG framework context in EL05?","options":["Nigeria relies only on voluntary CSR and has no sustainability frameworks.","The Nigerian Sustainable Banking Principles, NGX sustainability guidance, SEC sustainable finance guidance and Climate Change Act 2021 form part of the local context, while the Energy Transition Plan targets net-zero by 2060.","Only the Energy Transition Plan applies to Nigerian ESG reporting.","Nigeria has not begun implementation of IFRS sustainability disclosures."],"correct":2},
{"position":7,"question":"How does EL05 describe the role of ESG in project management decision-making?","options":["It focuses only on investor reporting after project close.","It removes the need for stakeholder engagement.","It helps reduce environmental impacts, improve resource efficiency, promote human rights and ethical governance, and strengthen resilience and project success.","It applies only to projects financed by international lenders."],"correct":3},
{"position":8,"question":"Which grouping correctly represents ESG risk categories in the module?","options":["Environmental—climate change, pollution, resource depletion; Social—labour practices, human rights, community relations; Governance—ethics, accountability, transparency and compliance.","Environmental—taxation; Social—exchange rates; Governance—weather.","Environmental—staffing; Social—energy use; Governance—biodiversity only.","Environmental—schedule; Social—budget; Governance—scope."],"correct":1},
{"position":9,"question":"Which option correctly matches the ESG metrics examples presented in EL05?","options":["Environmental—ethics; Social—emissions; Governance—water.","Environmental—profit only; Social—schedule; Governance—energy.","Environmental—emissions, energy, water and biodiversity; Social—diversity, welfare, safety and communities; Governance—ethics, compliance and risk management.","Environmental—headcount; Social—board oversight; Governance—pollution."],"correct":3},
{"position":10,"question":"What does sustainable project management require according to the EL05 module?","options":["Only environmental compliance during execution.","Stakeholder engagement across the lifecycle, resource efficiency, climate-conscious practices, accountability, transparency, ethical governance, continuous improvement and monitoring.","Only economic viability and profitability.","A one-time sustainability review during closing."],"correct":2},
{"position":11,"question":"Which statement distinguishes Life Cycle Assessment from Life Cycle Costing in EL05?","options":["LCA measures only acquisition cost while LCC measures emissions.","LCA and LCC are identical environmental reporting tools.","LCA applies only to social impacts while LCC applies only to governance.","Life Cycle Assessment evaluates environmental impacts across the entire lifecycle, while Life Cycle Costing measures acquisition, operation and disposal costs across the lifecycle."],"correct":4},
{"position":12,"question":"Which description best reflects green procurement and sustainable supply chains in EL05?","options":["Green procurement purchases environmentally friendly goods, while sustainable supply chains integrate ESG considerations through sourcing, contracting, transparency and collaboration.","They are limited to selecting the lowest-priced supplier.","They apply only after a supplier has completed delivery.","They eliminate the need for supplier engagement and data collection."],"correct":1},
{"position":13,"question":"What strategic benefit does EL05 associate with integrating ESG into business and project strategy?","options":["It guarantees that all project risks disappear.","It replaces financial and operational planning.","It strengthens risk management, innovation, organizational culture, investment attractiveness and long-term stakeholder value.","It limits stakeholder accountability to shareholders."],"correct":3},
{"position":14,"question":"Which future ESG trend is specifically highlighted in the module?","options":["Declining use of technology in ESG reporting.","Growing focus on climate, DEI and green finance, technology-enabled monitoring and transparent reporting, and movement toward mandatory disclosures in Nigeria.","Removal of diversity and inclusion from ESG practice.","A return from stakeholder capitalism to profit-only reporting."],"correct":2},
{"position":15,"question":"Which statement accurately reflects the Azura-Edo Independent Power Project case in EL05?","options":["It was presented as a solar mini-grid project with no resettlement concerns.","It avoided environmental and social audits to speed construction.","Its only ESG action was reducing procurement cost.","The $900 million, 461 MW gas-fired project addressed emissions, land/resettlement and local employment through safeguards, independent audits, local jobs and community programs, supporting international financing."],"correct":4},
{"position":16,"question":"What ESG response was emphasized in the Lekki Deep Sea Port case study?","options":["Environmental and Social Impact Assessments, resettlement and compensation, continuous stakeholder dialogue and grievance redress helped manage community and marine impacts.","The project excluded fishing communities from consultation to prevent delays.","The project relied only on financial disclosure.","The project avoided IFC standards and Nigerian environmental requirements."],"correct":1},
{"position":17,"question":"Which outcome is attributed to Solar Power Naija in the EL05 case study?","options":["It increased dependence on diesel generators in off-grid communities.","It focused only on imported technology and created no local employment.","It expanded clean-energy access, supported jobs and local industry, and reduced generator fuel costs, pollution and greenhouse gas emissions.","It was described as a gas-fired power project in Edo State."],"correct":3},
{"position":18,"question":"Which statement correctly describes Environmental Impact Assessment in Nigeria as presented in EL05?","options":["EIA is optional for environmentally significant national projects.","EIA is a legal requirement under the EIA Act 2004, originating as Decree No. 86 of 1992, and applies to environmentally significant sectors including oil, gas, mining, agriculture and infrastructure.","EIA applies only to privately financed projects.","EIA is solely a financial viability assessment."],"correct":2},
{"position":19,"question":"Which sequence contains core stages of the EIA process taught in EL05?","options":["Procurement, contracting, invoicing, arbitration and close-out.","Ideation, budgeting, recruitment and audit only.","Board approval, taxation, procurement and disclosure.","Screening, scoping, baseline data collection, impact prediction, mitigation planning, reporting, review, decision-making and monitoring."],"correct":4},
{"position":20,"question":"Which set contains key EIA principles explicitly listed in the module?","options":["Transparency, certainty, participation, practicability, flexibility, cost-effectiveness, credibility and accountability.","Secrecy, rigidity, speed, exclusivity and profit maximization.","Centralization, confidentiality, litigation and competition.","Procurement, scheduling, budgeting and quality control."],"correct":1},
{"position":21,"question":"How does EL05 characterize Social Impact Assessment and Corporate Social Responsibility?","options":["SIA measures only environmental emissions, while CSR is legally identical to EIA.","SIA evaluates social and cultural impacts using tools such as surveys and stakeholder mapping, while CSR consists of voluntary strategic actions supporting sustainable economic development and community well-being.","SIA and CSR are both limited to corporate tax reporting.","CSR eliminates the need for stakeholder engagement."],"correct":2},
{"position":22,"question":"Which governance statement is supported by EL05?","options":["Governance is limited to board meetings and excludes accountability.","CAMA 2020 is presented as an environmental impact law.","Good governance promotes transparency, accountability and ethical decision-making; CAMA 2020 addresses corporate governance, directors' responsibilities and shareholders' rights.","Governance frameworks do not influence investor confidence."],"correct":3},
{"position":23,"question":"Which compliance combination is specifically identified in EL05?","options":["Nigeria applies only international voluntary standards with no local frameworks.","The UK Bribery Act and U.S. FCPA are presented as Nigerian tax statutes.","Non-compliance is described as having no reputational consequences.","Nigeria applies SEC, FRCN and FIRS frameworks, while global anti-bribery compliance examples include the UK Bribery Act and U.S. FCPA."],"correct":4},
{"position":24,"question":"What does effective ESG reporting and stakeholder engagement require according to EL05?","options":["Timely, accurate and balanced disclosure plus early two-way dialogue, stakeholder mapping, consultations and grievance systems.","Annual financial reporting without community communication.","One-way announcements after project completion.","Avoiding NGOs, employees and communities during stakeholder identification."],"correct":1},
{"position":25,"question":"How should ESG be integrated across the project life cycle according to the final EL05 lesson?","options":["ESG begins only after project authorization and ends before execution.","ESG is assessed at ideation, integrated into objectives and governance at initiation, planned through strategies/KPIs/mitigation, implemented during execution, tracked during monitoring, and reported with lessons learned at closing.","ESG belongs exclusively to ideation and should not continue into initiation.","ESG is relevant only during monitoring and controlling."],"correct":2}
]
$mcq$::jsonb;
  v_item jsonb; v_qid uuid; v_opt_id uuid; v_correct_id uuid; v_option_text text; v_opt_pos integer;
begin
  for v_item in select value from jsonb_array_elements(v_mcqs) loop
    v_qid := public.cipmn_mock_seed_uuid('CIPMN-MOD-EL05:MCQ:' || (v_item->>'position'));
    insert into public.questions(id,examination_id,question_text,question_type,section,position,points,is_active) values(v_qid,v_exam_id,v_item->>'question','single_choice','mcq',(v_item->>'position')::integer,1,true);
    v_correct_id := null;
    for v_option_text,v_opt_pos in select value #>> '{}', ordinality::integer from jsonb_array_elements(v_item->'options') with ordinality loop
      insert into public.question_options(question_id,option_text,position) values(v_qid,v_option_text,v_opt_pos) returning id into v_opt_id;
      if v_opt_pos=(v_item->>'correct')::integer then v_correct_id:=v_opt_id; end if;
    end loop;
    if v_correct_id is null then raise exception 'No correct option resolved for EL05 MCQ position %.',v_item->>'position'; end if;
    insert into public.question_answer_keys(question_id,correct_option_id) values(v_qid,v_correct_id);
  end loop;
end
$mcq_insert$;

do $theory_insert$
declare
  v_exam_id constant uuid := public.cipmn_mock_seed_uuid('CIPMN-MOD-EL05:EXAM');
  v_theory jsonb := $theory$
[
{"position":26,"question":"Using only EL05: (a) define ESG and distinguish ESG from sustainability; (b) explain the Environmental, Social and Governance pillars; (c) trace the history from early CSR through the Triple Bottom Line, GRI, PRI, SASB/TCFD, SDGs and ISSB; (d) explain IFRS S1 and IFRS S2 and Nigeria's adoption context; and (e) explain the transition from shareholder to stakeholder capitalism.","criteria":[{"name":"ESG and sustainability","marks":2,"expected":"Defines ESG as Environmental, Social and Governance performance and explains sustainability as balancing economy, environment and social equity."},{"name":"Three pillars","marks":2,"expected":"Explains environmental climate/pollution/resources, social communities/workers/equity, and governance accountability/board oversight/transparency."},{"name":"Historical evolution","marks":2,"expected":"Covers early CSR, Brundtland 1987, Triple Bottom Line People/Planet/Profit 1994, Global Reporting Initiative 1997, PRI 2006, Sustainability Accounting Standards Board and Task Force on Climate-related Financial Disclosures, and SDGs."},{"name":"ISSB disclosures and Nigeria","marks":2,"expected":"Explains International Sustainability Standards Board creation in 2021, IFRS S1 and IFRS S2 in 2023, and Nigeria's FRC/ISSB/NGX RegCo adoption context."},{"name":"Stakeholder capitalism","marks":2,"expected":"Explains the shift from profit-focused shareholder capitalism toward accountability to customers, employees, investors, regulators, communities and society."}]},
{"position":27,"question":"Using only EL05: (a) explain major ESG frameworks and standards; (b) explain the Nigerian Sustainable Banking Principles, NGX guidance, SEC sustainable finance guidance and Climate Change Act 2021; (c) explain Nigeria's Energy Transition Plan and net-zero 2060 direction; (d) explain ESG risk assessment and metrics/reporting; and (e) explain how ESG strengthens project and business strategy.","criteria":[{"name":"Global frameworks","marks":2,"expected":"Explains Global Reporting Initiative, Sustainability Accounting Standards Board, Task Force on Climate-related Financial Disclosures, ISSB and IFRS S1/IFRS S2 at the source's level."},{"name":"Nigerian frameworks","marks":2,"expected":"Explains Nigerian Sustainable Banking Principles, NGX Sustainability Disclosure Guidelines, SEC sustainable finance guidance and Climate Change Act 2021."},{"name":"Energy transition","marks":2,"expected":"Explains the Energy Transition Plan's renewable-energy direction and roadmap toward net-zero greenhouse gas emissions by 2060."},{"name":"Risk and metrics","marks":2,"expected":"Explains environmental, social and governance risks plus environmental emissions/energy/water/biodiversity, social diversity/welfare/safety/community, and governance ethics/compliance/risk metrics."},{"name":"Strategic value","marks":2,"expected":"Explains resilience, reputation, stakeholder trust, innovation, sustainable investment attraction, competitiveness and long-term value."}]},
{"position":28,"question":"Using only EL05: (a) explain sustainable project management principles; (b) compare Life Cycle Assessment and Life Cycle Costing; (c) explain green procurement and sustainable supply chains; (d) analyse the Azura-Edo IPP, Lekki Deep Sea Port and Solar Power Naija case studies; and (e) apply the Triple Bottom Line to one of those cases.","criteria":[{"name":"Sustainable PM","marks":2,"expected":"Explains stakeholder engagement, minimized environmental impact, social well-being/equity, economic viability, transparency/accountability/ethical governance, innovation and monitoring."},{"name":"Life-cycle approaches","marks":2,"expected":"Distinguishes Life Cycle Assessment environmental impacts from Life Cycle Costing acquisition/operation/disposal costs and notes data/method complexity and ISO consistency."},{"name":"Green procurement/supply chains","marks":2,"expected":"Explains environmentally friendly purchasing and ESG-integrated sourcing, contracting, transparency and collaboration, including supplier/data challenges."},{"name":"Nigerian cases","marks":2,"expected":"Uses source-supported Azura-Edo safeguards/jobs/community programs, Lekki ESIA/resettlement/dialogue/grievance mechanisms, and Solar Power Naija clean-energy/access/jobs/pollution-reduction lessons."},{"name":"Triple Bottom Line application","marks":2,"expected":"Applies People, Planet and Profit to a source case without importing outside facts."}]},
{"position":29,"question":"Using only EL05: (a) explain Environmental Impact Assessment in Nigeria and its legal basis; (b) explain screening, scoping, baseline data, impact prediction, mitigation, reporting, review, decision-making and monitoring; (c) explain EIA principles and methodologies; (d) explain Social Impact Assessment and stakeholder methods; and (e) explain Corporate Social Responsibility in the Nigerian context.","criteria":[{"name":"EIA legal basis","marks":2,"expected":"Explains EIA as a legal requirement under the EIA Act 2004 originating as Decree No. 86 (1992), applicable to environmentally significant projects."},{"name":"EIA process","marks":2,"expected":"Explains screening, scoping, baseline data collection, impact prediction, mitigation planning, reporting, review, decision-making and monitoring."},{"name":"Principles/methods","marks":2,"expected":"Explains transparency, certainty, participation, practicability, flexibility, cost-effectiveness, credibility and accountability plus baseline/prediction, evaluation and mitigation/management methodologies."},{"name":"Social Impact Assessment","marks":2,"expected":"Explains social/cultural impact evaluation, surveys, appraisals, stakeholder mapping, consultations, inclusivity and FPIC."},{"name":"CSR","marks":2,"expected":"Explains voluntary strategic actions supporting sustainable economic development, workers/communities, trust, reduced unrest and sustained operations."}]},
{"position":30,"question":"Using only EL05: (a) explain governance structures and frameworks including CAMA 2020; (b) explain compliance requirements including SEC, FRCN, FIRS, UK Bribery Act and FCPA; (c) explain ESG reporting and disclosure; (d) explain stakeholder identification, dialogue and grievance mechanisms; and (e) show how ESG applies from ideation through initiation, planning, execution, monitoring and closing.","criteria":[{"name":"Governance","marks":2,"expected":"Explains transparency, accountability, ethical decision-making, authority/oversight and CAMA 2020 responsibilities/rights, with OECD/UK governance benchmarks at source level."},{"name":"Compliance","marks":2,"expected":"Explains SEC, FRCN and FIRS frameworks, Oil and Gas Content Act, sanctions/reputational risk, UK Bribery Act and U.S. FCPA examples."},{"name":"Reporting/disclosure","marks":2,"expected":"Explains accountability, GRI/SASB/NGX guidance, IFRS/FRCN compliance, and timely accurate balanced reporting."},{"name":"Stakeholder engagement","marks":2,"expected":"Explains mapping agencies, communities, employees and NGOs; consultations/hearings/town halls; two-way dialogue, cultural respect and grievance systems; engagement as cyclical."},{"name":"Lifecycle integration","marks":2,"expected":"Explains ESG assessment at ideation, objectives/governance at initiation, strategies/KPIs/mitigation in planning, responsible practices in execution, performance/compliance in monitoring, and outcomes/lessons at closing."}]}
]
$theory$::jsonb;
  v_item jsonb; v_qid uuid;
begin
  for v_item in select value from jsonb_array_elements(v_theory) loop
    v_qid := public.cipmn_mock_seed_uuid('CIPMN-MOD-EL05:THEORY:' || ((v_item->>'position')::integer-25));
    insert into public.questions(id,examination_id,question_text,question_type,section,position,points,is_active) values(v_qid,v_exam_id,v_item->>'question','theory','theory',(v_item->>'position')::integer,10,true);
    insert into public.theory_marking_rubrics(question_id,max_score,rubric,source_label,is_active) values(v_qid,10,jsonb_build_object('criteria',v_item->'criteria'),'CIPMN-MOD-EL05.pptx (46 slides/pages; reviewed 2026-09-26)',true);
  end loop;
end
$theory_insert$;

do $commerce_and_proctoring$
declare v_exam_id constant uuid := public.cipmn_mock_seed_uuid('CIPMN-MOD-EL05:EXAM');
begin
  insert into public.agilecert_exam_pricing_policies(id,examination_id,currency,standard_amount_minor,promotional_amount_minor,promotion_name,promotion_starts_at,promotion_ends_at,access_mode,attempts_included,retake_amount_minor,bulk_cart_eligible,is_active,updated_by)
  values(public.cipmn_mock_seed_uuid('CIPMN-MOD-EL05:PRICING-POLICY'),v_exam_id,'NGN',2500000,null,null,null,null,'paid',1,null,true,true,null);
  update public.agilecert_identity_proctoring_policies set policy_version=2,consent_version='cipmn-camera-v1',privacy_notice='Identity and proctoring data is used only to protect examination integrity, investigate incidents and meet certification obligations.',require_existing_identity_approval=false,require_government_id=false,require_selfie=false,require_exam_day_identity_check=false,require_camera=true,require_microphone_permission=false,require_fullscreen=false,live_event_capture_enabled=true,ai_visual_analysis_enabled=true,external_kyc_enabled=false,automated_face_match_enabled=false,liveness_check_enabled=false,retain_webcam_images=false,incident_threshold=60.00,critical_threshold=80.00,low_event_weight=2.00,medium_event_weight=8.00,high_event_weight=20.00,identity_retention_days=365,proctor_event_retention_days=365,incident_retention_days=730,appeal_window_days=14,active=true,updated_by=null,updated_at=now() where examination_id=v_exam_id;
end
$commerce_and_proctoring$;

do $verify$
declare
  v_exam_id constant uuid := public.cipmn_mock_seed_uuid('CIPMN-MOD-EL05:EXAM'); v_mcq integer; v_theory integer; v_keys integer; v_options integer; v_rubrics integer; v_bad_options integer; v_bad_rubrics integer; v_duplicate_texts integer; v_policy integer; v_pricing integer;
begin
  select count(*) into v_mcq from public.questions where examination_id=v_exam_id and is_active and section='mcq' and question_type='single_choice';
  select count(*) into v_theory from public.questions where examination_id=v_exam_id and is_active and section='theory' and question_type='theory';
  select count(*) into v_keys from public.question_answer_keys k join public.questions q on q.id=k.question_id where q.examination_id=v_exam_id and q.is_active and q.section='mcq';
  select count(*) into v_options from public.question_options o join public.questions q on q.id=o.question_id where q.examination_id=v_exam_id and q.is_active and q.section='mcq';
  select count(*) into v_rubrics from public.theory_marking_rubrics r join public.questions q on q.id=r.question_id where q.examination_id=v_exam_id and q.is_active and q.section='theory' and r.is_active;
  select count(*) into v_bad_options from public.questions q where q.examination_id=v_exam_id and q.is_active and q.section='mcq' and ((select count(*) from public.question_options o where o.question_id=q.id)<>4 or (select count(distinct lower(trim(o.option_text))) from public.question_options o where o.question_id=q.id)<>4);
  select count(*) into v_bad_rubrics from public.theory_marking_rubrics r join public.questions q on q.id=r.question_id where q.examination_id=v_exam_id and q.is_active and q.section='theory' and (not r.is_active or r.max_score<>10 or jsonb_typeof(r.rubric->'criteria')<>'array' or jsonb_array_length(r.rubric->'criteria')<>5);
  select count(*)-count(distinct regexp_replace(lower(trim(question_text)),'\s+',' ','g')) into v_duplicate_texts from public.questions where examination_id=v_exam_id and is_active;
  select count(*) into v_policy from public.agilecert_identity_proctoring_policies where examination_id=v_exam_id and active=true and require_camera=true and live_event_capture_enabled=true and ai_visual_analysis_enabled=true;
  select count(*) into v_pricing from public.agilecert_exam_pricing_policies where examination_id=v_exam_id and is_active=true and currency='NGN' and standard_amount_minor=2500000 and access_mode='paid';
  if v_mcq<>25 then raise exception 'Expected 25 active EL05 MCQs, found %.',v_mcq; end if; if v_theory<>5 then raise exception 'Expected 5 active EL05 Theory questions, found %.',v_theory; end if; if v_keys<>25 then raise exception 'Expected 25 EL05 answer keys, found %.',v_keys; end if; if v_options<>100 then raise exception 'Expected 100 EL05 MCQ options, found %.',v_options; end if; if v_rubrics<>5 then raise exception 'Expected 5 EL05 Theory rubrics, found %.',v_rubrics; end if; if v_bad_options<>0 then raise exception 'Found % EL05 MCQ(s) with invalid/repeated options.',v_bad_options; end if; if v_bad_rubrics<>0 then raise exception 'Found % invalid EL05 Theory rubric(s).',v_bad_rubrics; end if; if v_duplicate_texts<>0 then raise exception 'Found % repeated active EL05 question text(s).',v_duplicate_texts; end if; if v_policy<>1 then raise exception 'EL05 proctoring policy invariant failed.'; end if; if v_pricing<>1 then raise exception 'EL05 pricing policy invariant failed.'; end if;
end
$verify$;

update public.examinations set exam_format='cipmn_mixed',status='published',updated_at=now() where id=public.cipmn_mock_seed_uuid('CIPMN-MOD-EL05:EXAM');

do $publish_verify$
declare v_exam_id constant uuid := public.cipmn_mock_seed_uuid('CIPMN-MOD-EL05:EXAM'); v_prices integer; v_published integer;
begin
  select count(*) into v_prices from public.exam_prices where examination_id=v_exam_id and is_active and ((currency='NGN' and amount_minor=2500000 and is_default=true) or (currency='USD' and amount_minor=5000 and is_default=false));
  select count(*) into v_published from public.examinations where id=v_exam_id and status='published' and exam_format='cipmn_mixed' and requires_payment=true and allow_self_enrollment=false;
  if v_prices<>2 then raise exception 'Expected publish trigger to create 2 active EL05 prices, found %.',v_prices; end if; if v_published<>1 then raise exception 'EL05 publish invariant failed.'; end if;
end
$publish_verify$;

commit;
