begin;
-- CIPMN-MOD-EL06 — Managing Successful International Programs and Portfolios
-- Sole source: CIPMN-MOD-012.pptx (39 slides/pages), treated as Elective 6.
do $guard$ declare x uuid:=public.cipmn_mock_seed_uuid('CIPMN-MOD-EL06:EXAM');begin if exists(select 1 from public.examinations where id=x or upper(code)='CIPMN-MOD-EL06')then raise exception 'EL06 exists';end if;end $guard$;
do $exam$ declare x uuid:=public.cipmn_mock_seed_uuid('CIPMN-MOD-EL06:EXAM');begin insert into public.examinations(id,programme_id,title,instructions,duration_minutes,pass_mark,status,max_attempts,randomize_questions,randomize_options,allow_self_enrollment,requires_payment,code,exam_format)values(x,'614ea9d4-0bd4-5df5-a817-9a93937c74e3','CIPMN-MOD-EL06 - Managing Successful International Programs and Portfolios Mock Examination','Complete 25 MCQs then 5 Theory questions. MCQ contributes 40% and Theory 60%.',120,70,'draft',3,true,true,false,true,'CIPMN-MOD-EL06','standard');end $exam$;
do $mcq_insert$ declare x uuid:=public.cipmn_mock_seed_uuid('CIPMN-MOD-EL06:EXAM');j jsonb:=$mcq$
[
{"position":1,"question":"What does international development programming seek to improve in under-resourced regions?","options":["Profit only","Economic, social and environmental well-being","Audit speed","Tax revenue"],"correct":2},
{"position":2,"question":"Which activities support needs-driven and context-specific international programme design?","options":["Baseline surveys, needs assessment and community consultations","Litigation","Desk research only","Dividend analysis"],"correct":1},
{"position":3,"question":"Who should participate in programme design, decision-making and evaluation under EL06?","options":["Consultants only","Donors only","Communities, civil society, government agencies and beneficiaries","Accountants only"],"correct":3},
{"position":4,"question":"How should international programmes align with global and national priorities?","options":["Ignore policy","Use donor preferences only","Map budgets only","Map Sustainable Development Goals targets and national/sector policies"],"correct":4},
{"position":5,"question":"Which practice reflects evidence-based planning and decision-making in EL06?","options":["Use reliable data, research, lessons, government statistics and donor reports","Use intuition","Avoid monitoring","Exclude research"],"correct":1},
{"position":6,"question":"Which approach reflects results-oriented management and sustainability in EL06?","options":["End benefits with funding","Avoid government systems","Use frameworks, theories and SMART indicators while building local capability","Measure activities only"],"correct":3},
{"position":7,"question":"What does accountability and transparency require in donor-supported programmes?","options":["Confidential decisions","Openness, reports, accountability meetings, financial controls and audits","Closure-only reports","No audits"],"correct":2},
{"position":8,"question":"Which response best represents flexibility and adaptive management when conditions change?","options":["Freeze plans","Stop monitoring","Avoid adjustments","Flexible contracts/work plans and real-time monitoring adjustments"],"correct":4},
{"position":9,"question":"How does EL06 define a Theory of Change for international programme design?","options":["A description and visual link from activities to outcomes and impacts with assumptions","Price comparison","Invoice list","Schedule only"],"correct":1},
{"position":10,"question":"In the maternal-health Theory of Change example, what output follows training midwives?","options":["Reduced mortality","Safer deliveries","Increased skilled birth attendance","Scorecards"],"correct":3},
{"position":11,"question":"Which four levels form the Logical Framework hierarchy presented in EL06?","options":["Risk, Issue, Change, Benefit","Goal, Purpose/Outcome, Outputs, Activities","Vision, Mission, Budget, Audit","Scope, Time, Cost, Quality"],"correct":2},
{"position":12,"question":"What additional elements does the Logical Framework require for monitoring?","options":["Narrative only","Names only","Funding only","Indicators, means of verification, assumptions and risks"],"correct":4},
{"position":13,"question":"What role do SWOT, PESTEL and Stakeholder Mapping play in programme design?","options":["Understand environment, risks, opportunities and partners","Replace all frameworks","Audit only","Contract selection"],"correct":1},
{"position":14,"question":"Which action supports understanding cultural traits across multinational portfolios?","options":["One leadership style","Exclude locals","Study values and behaviours, adapt communication, involve locals and assess cultural risk","Avoid training"],"correct":3},
{"position":15,"question":"What is recommended for governance in culturally diverse donor-driven settings?","options":["Donor rules only","Local involvement, donor alignment, clear roles and feedback channels","No procedures","Ignore culture"],"correct":2},
{"position":16,"question":"How should compliance, value delivery and strategy be managed in diverse teams?","options":["Informally","Without indicators","Externally only","Guidelines, training, indicators, inclusive communication, monitoring and collaboration"],"correct":4},
{"position":17,"question":"What is the purpose of feedback systems for adaptive learning in global portfolios?","options":["Analyse feedback, generate insights, adjust strategy and share learning","Store only","Prevent changes","Limit learning"],"correct":1},
{"position":18,"question":"Which practices support knowledge transfer and continuous improvement across geographies?","options":["Restrict practices","Workshops, webinars, peer learning, mentoring and planning cycles","Avoid sharing","Audits only"],"correct":2},
{"position":19,"question":"What central portfolio principle applies to donor-funded and multicountry projects?","options":["Isolation","Uniformity","Strategic alignment, resource optimization and overall portfolio value","No governance"],"correct":3},
{"position":20,"question":"Which set describes donor compliance and audit readiness requirements in EL06?","options":["Optional rules","No documentation","Finance ethics only","Donor guidelines, financial procedures, checks, staff training and audit documentation"],"correct":4},
{"position":21,"question":"What does strategic partner management require when using MoUs and sub-granting?","options":["MoUs, commitments, reporting, deliverables, financial rules, monitoring and communication","Verbal terms","No reporting","No coordination"],"correct":1},
{"position":22,"question":"How does programme sustainability connect local ownership with measurable exit criteria?","options":["Exit unprepared","Engage locals, build skills, transfer tools, define exit criteria and monitor transition","Retain skills externally","Use payment date"],"correct":2},
{"position":23,"question":"Which action belongs to risk assessment and mitigation for partnership/compliance failures?","options":["Wait for failure","Avoid agreements","Assess risks, clarify agreements, train, audit, resolve conflicts and prepare contingencies","No reviews"],"correct":3},
{"position":24,"question":"How should conflict resolution be handled in culturally diverse multi-country teams?","options":["Impose one style","Delay conflicts","Avoid mediation","Respectful communication, cultural awareness, neutral mediators and early procedures"],"correct":4},
{"position":25,"question":"Which statement best captures sustainability as an exit strategy in EL06?","options":["Transfer ownership, capacity and resources locally against measurable exit criteria","Plan after funding","Undefined exit","No local ownership"],"correct":1}
]
$mcq$::jsonb;q jsonb;qid uuid;oid uuid;cid uuid;t text;p int;begin for q in select value from jsonb_array_elements(j)loop qid:=public.cipmn_mock_seed_uuid('CIPMN-MOD-EL06:MCQ:'||(q->>'position'));insert into public.questions(id,examination_id,question_text,question_type,section,position,points,is_active)values(qid,x,q->>'question','single_choice','mcq',(q->>'position')::int,1,true);for t,p in select value#>>'{}',ordinality::int from jsonb_array_elements(q->'options')with ordinality loop insert into public.question_options(question_id,option_text,position)values(qid,t,p)returning id into oid;if p=(q->>'correct')::int then cid:=oid;end if;end loop;insert into public.question_answer_keys(question_id,correct_option_id)values(qid,cid);end loop;end $mcq_insert$;
commit;
